-- PostgreSQL inventory model mirrored for repository/bootstrap parity.
-- Apply through Supabase migrations in deployed environments.

create table if not exists public.vehicles (
  vehicle_id uuid primary key default gen_random_uuid(),
  identity_key text not null unique,
  brand text not null,
  model text not null,
  variant text,
  manufacture_year integer,
  registration_year integer,
  manufacture_date date,
  registration_date date,
  condition text not null default 'used' check (condition in ('used','demo','unknown')),
  fuel text,
  transmission text,
  seller_city text,
  seller_state text,
  registration_state text,
  status text not null default 'unknown' check (status in ('active','stale','removed','sold','unknown')),
  identity_confidence numeric(5,4) not null default 0,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.listings (
  listing_id uuid primary key default gen_random_uuid(),
  source_id uuid not null references public.sources(source_id) on delete restrict,
  vehicle_id uuid references public.vehicles(vehicle_id) on delete set null,
  source_listing_key text not null,
  url text not null,
  final_url text,
  title text,
  seller_name text,
  seller_city text,
  seller_state text,
  condition text not null default 'unknown' check (condition in ('used','demo','unknown')),
  status text not null default 'active' check (status in ('active','stale','removed','sold','unknown')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique(source_id, source_listing_key)
);

create table if not exists public.vehicle_observations (
  observation_id bigint generated by default as identity primary key,
  vehicle_id uuid not null references public.vehicles(vehicle_id) on delete cascade,
  listing_id uuid references public.listings(listing_id) on delete set null,
  source_id uuid not null references public.sources(source_id) on delete restrict,
  observed_at timestamptz not null default now(),
  price_lakh numeric(12,2),
  mileage_km integer,
  owner_count integer,
  manufacture_year integer,
  registration_year integer,
  seller_city text,
  seller_state text,
  registration_state text,
  live_verified boolean not null default false,
  data_consistent boolean not null default true,
  sold_signal boolean not null default false,
  identity_confidence numeric(5,4) not null default 0,
  snapshot jsonb not null default '{}'::jsonb
);

create index if not exists idx_vehicles_search on public.vehicles (brand, model, condition, status);
create index if not exists idx_vehicles_last_seen on public.vehicles (last_seen_at desc);
create index if not exists idx_listings_vehicle on public.listings(vehicle_id);
create index if not exists idx_listings_source_status on public.listings(source_id, status, last_seen_at desc);
create index if not exists idx_observations_vehicle_time on public.vehicle_observations(vehicle_id, observed_at desc);
create index if not exists idx_observations_source_time on public.vehicle_observations(source_id, observed_at desc);
create index if not exists idx_observations_price on public.vehicle_observations(price_lakh) where price_lakh is not null;
